#!/usr/bin/env node
/**
 * Rick & Morty AI Executor — build tool.
 *
 * Roblox executors consume a single chunk, so this bundles every module under
 * `src/` into one pasteable file at `dist/rick-morty-executor.lua`.
 *
 * Modules are plain Luau files that `return` a table and call
 * `require("core/Example")`. The bundle installs a tiny module registry so the
 * exact same source runs unbundled inside a dev harness.
 *
 * Files under `bridge/` are inlined as raw text assets (see `bundle/assets`).
 *
 * Usage:
 *   node build.js           validate + bundle
 *   node build.js --check   validate only
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const BRIDGE = path.join(ROOT, 'bridge');
const DIST = path.join(ROOT, 'dist');
const ENTRY = 'init';
const OUT_FILE = path.join(DIST, 'rick-morty-executor.lua');

const checkOnly = process.argv.includes('--check');
const PKG_PATH = path.join(ROOT, 'package.json');
const README_PATH = path.join(ROOT, 'README.md');
const INSTALL_FILE = path.join(DIST, 'install.lua');
const OUT_FILE_NAME = path.basename(OUT_FILE);

// Markers delimiting the block build.js owns in README.md.
const BEGIN_MARK = '<!-- BEGIN:INSTALL -->';
const END_MARK = '<!-- END:INSTALL -->';

/* ------------------------------------------------- install URL resolution */

/**
 * Owner/repo/version come from package.json so the raw URL only ever has one
 * source of truth. Returns null when the repository field is unusable.
 */
function repoCoordinates() {
  let pkg;
  try {
    pkg = JSON.parse(fs.readFileSync(PKG_PATH, 'utf8'));
  } catch (error) {
    return null;
  }

  const repository = pkg.repository || {};
  const url = typeof repository === 'string' ? repository : repository.url || '';
  const match = String(url).match(/github\.com[/:]([^/]+)\/([^/]+?)(?:\.git)?$/);

  if (!match) return null;

  return {
    owner: match[1],
    repo: match[2],
    version: pkg.version || '0.0.0',
    branch: (typeof repository === 'object' && repository.branch) || 'main',
  };
}

function rawUrls() {
  const coords = repoCoordinates();
  if (!coords) return null;

  const base = `https://raw.githubusercontent.com/${coords.owner}/${coords.repo}`;
  const repoUrl = `https://github.com/${coords.owner}/${coords.repo}`;

  return {
    coords,
    repoUrl,
    latest: `${base}/${coords.branch}/dist/${OUT_FILE_NAME}`,
    pinned: `${base}/v${coords.version}/dist/${OUT_FILE_NAME}`,
    blobUrl: `${repoUrl}/blob/${coords.branch}/dist/${OUT_FILE_NAME}`,
  };
}

function oneLiner(url) {
  return `loadstring(game:HttpGet("${url}"))()`;
}

/* --------------------------------------------------- generated artifacts */

/**
 * The wording stays tag-agnostic on purpose: build.js only knows package.json, and
 * a machine that has not fetched tags would otherwise generate a different block
 * and make `--check` report phantom drift.
 */
function renderInstallBlock(urls) {
  return [
    BEGIN_MARK,
    '<!-- Generated by build.js from package.json - do not edit by hand. -->',
    '',
    '## Install',
    '',
    'Paste this into your executor and run it:',
    '',
    '```lua',
    oneLiner(urls.latest),
    '```',
    '',
    `That always pulls the newest build from \`${urls.coords.branch}\`. Release tags pin a`,
    `build that never changes - \`v${urls.coords.version}\` is the current one:`,
    '',
    '```lua',
    oneLiner(urls.pinned),
    '```',
    '',
    `Tagged builds come from the same \`package.json\` version, so bumping it and pushing`,
    `\`v<version>\` updates this block and the pinned URL together.`,
    '',
    `Prefer to read the source first? Grab [\`dist/${OUT_FILE_NAME}\`](${urls.blobUrl}) and paste it in manually.`,
    '',
    'The bundle inlines every module plus the Cowork bridge payload, so the one-liner is the',
    'entire install: no loader, no module chain, no external dependencies.',
    '',
    END_MARK,
  ].join('\n');
}

function renderInstallFile(urls) {
  return [
    '--[[',
    '\tRick & Morty AI Executor - one-line install.',
    '\tGenerated by build.js. Paste this whole file into your executor and run it.',
    '',
    `\tlatest  : ${urls.latest}`,
    `\tpin to v${urls.coords.version}: ${urls.pinned}`,
    ']]',
    '',
    oneLiner(urls.latest),
    '',
  ].join('\n');
}

/**
 * Rewrites the block between the INSTALL markers in README.md.
 * Returns 'updated' | 'unchanged' | 'missing-markers'.
 */
function syncReadme(urls, write) {
  if (!urls || !fs.existsSync(README_PATH)) return 'missing-markers';

  const source = fs.readFileSync(README_PATH, 'utf8');
  const start = source.indexOf(BEGIN_MARK);
  const end = source.indexOf(END_MARK);

  if (start === -1 || end === -1 || end < start) return 'missing-markers';

  const block = renderInstallBlock(urls);
  const next = source.slice(0, start) + block + source.slice(end + END_MARK.length);

  if (next === source) return 'unchanged';
  if (write) fs.writeFileSync(README_PATH, next, 'utf8');
  return 'updated';
}

/* ------------------------------------------------------------------ files */

function walk(dir, out = []) {
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

function moduleId(file) {
  return path.relative(SRC, file).replace(/\\/g, '/').replace(/\.lua$/, '');
}

function countNewlines(text) {
  let count = 0;
  for (let i = 0; i < text.length; i++) if (text[i] === '\n') count++;
  return count;
}

/* -------------------------------------------------------------- tokenizer */

/**
 * Minimal Luau tokenizer. Strips comments and strings so the block checker
 * below never mistakes their contents for keywords.
 */
function tokenize(source, file) {
  const tokens = [];
  const length = source.length;
  let index = 0;
  let line = 1;

  const longBracket = (at) => {
    if (source[at] !== '[') return null;
    let cursor = at + 1;
    let level = 0;
    while (source[cursor] === '=') {
      level++;
      cursor++;
    }
    if (source[cursor] !== '[') return null;
    return { level, contentStart: cursor + 1 };
  };

  while (index < length) {
    const char = source[index];

    if (char === '\n') {
      line++;
      index++;
      continue;
    }
    if (char === ' ' || char === '\t' || char === '\r') {
      index++;
      continue;
    }

    // Comments (line, long) and long strings share the `[=*[` delimiter.
    if (char === '-' && source[index + 1] === '-') {
      const bracket = longBracket(index + 2);
      if (bracket) {
        const close = ']' + '='.repeat(bracket.level) + ']';
        const end = source.indexOf(close, bracket.contentStart);
        if (end === -1) return { error: `${file}:${line}: unterminated long comment` };
        line += countNewlines(source.slice(index, end + close.length));
        index = end + close.length;
      } else {
        while (index < length && source[index] !== '\n') index++;
      }
      continue;
    }

    if (char === '[') {
      const bracket = longBracket(index);
      if (bracket) {
        const close = ']' + '='.repeat(bracket.level) + ']';
        const end = source.indexOf(close, bracket.contentStart);
        if (end === -1) return { error: `${file}:${line}: unterminated long string` };
        line += countNewlines(source.slice(index, end + close.length));
        index = end + close.length;
        continue;
      }
    }

    if (char === '"' || char === "'") {
      let cursor = index + 1;
      while (cursor < length) {
        if (source[cursor] === '\\') {
          cursor += 2;
          continue;
        }
        if (source[cursor] === char) break;
        if (source[cursor] === '\n') return { error: `${file}:${line}: unterminated string` };
        cursor++;
      }
      if (cursor >= length) return { error: `${file}:${line}: unterminated string` };
      index = cursor + 1;
      continue;
    }

    if (/[A-Za-z_]/.test(char)) {
      let cursor = index;
      while (cursor < length && /[A-Za-z0-9_]/.test(source[cursor])) cursor++;
      tokens.push({ type: 'name', value: source.slice(index, cursor), line });
      index = cursor;
      continue;
    }

    if (/[0-9]/.test(char) || (char === '.' && /[0-9]/.test(source[index + 1] || ''))) {
      let cursor = index;
      while (cursor < length && /[0-9a-fA-FxX._]/.test(source[cursor])) cursor++;
      tokens.push({ type: 'number', value: source.slice(index, cursor), line });
      index = cursor;
      continue;
    }

    tokens.push({ type: 'symbol', value: char, line });
    index++;
  }

  return { tokens };
}

/* ------------------------------------------------------------ validation */

const PAIRS = { '(': ')', '[': ']', '{': '}' };

/**
 * Locals are only visible *after* their declaration. A read above it is not a
 * forward reference in Lua - it compiles to a global lookup, which is nil. This
 * is how `panel:clear()` a few lines above `local panel = {}` shipped: it parses,
 * it loads, and it worked until a player pressed the button, then raised
 * "attempt to index nil with 'clear'".
 *
 * Parameters and `for` variables bind where they appear and are exempt, since a
 * read "before" one of those is ordinary shadowing.
 */
function validateForwardLocals(file, tokens) {
  const declaredAt = new Map();
  const boundAt = new Map();
  const declarations = new Set();

  const bind = (map, name, line) => {
    if (!map.has(name) || line < map.get(name)) map.set(name, line);
  };

  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.type !== 'name') continue;

    if (token.value === 'local') {
      const isFunction = tokens[i + 1] && tokens[i + 1].value === 'function';
      let cursor = i + 1 + (isFunction ? 1 : 0);

      while (tokens[cursor] && tokens[cursor].type === 'name') {
        bind(declaredAt, tokens[cursor].value, token.line);
        declarations.add(cursor);
        if (isFunction) break;
        cursor++;
        if (tokens[cursor] && tokens[cursor].value === ':') cursor += 2; // `: Type`
        if (tokens[cursor] && tokens[cursor].value === ',') {
          cursor++;
          continue;
        }
        break;
      }
      continue;
    }

    if (token.value === 'for') {
      let cursor = i + 1;
      while (tokens[cursor] && tokens[cursor].type === 'name') {
        bind(boundAt, tokens[cursor].value, token.line);
        declarations.add(cursor);
        cursor++;
        if (tokens[cursor] && tokens[cursor].value === ',') {
          cursor++;
          continue;
        }
        break;
      }
      continue;
    }

    if (token.value === 'function') {
      // Step over `name`, `a.b` and `a:b` to reach the parameter list.
      let cursor = i + 1;
      while (tokens[cursor] && tokens[cursor].type === 'name') {
        cursor++;
        if (tokens[cursor] && (tokens[cursor].value === '.' || tokens[cursor].value === ':')) {
          cursor++;
          continue;
        }
        break;
      }
      if (!tokens[cursor] || tokens[cursor].value !== '(') continue;

      let depth = 0;
      let expectName = true;

      for (let j = cursor; j < tokens.length; j++) {
        const inner = tokens[j];

        if (inner.value === '(') {
          depth++;
          continue;
        }
        if (inner.value === ')') {
          depth--;
          if (depth === 0) break;
          continue;
        }
        if (depth !== 1) continue;
        if (inner.value === ',') {
          expectName = true;
          continue;
        }
        if (inner.value === ':') {
          expectName = false; // type annotation
          continue;
        }
        if (inner.type === 'name' && expectName) {
          bind(boundAt, inner.value, token.line);
          declarations.add(j);
          expectName = false;
        }
      }
      continue;
    }
  }

  const errors = [];

  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.type !== 'name') continue;

    const declared = declaredAt.get(token.value);
    if (declared === undefined) continue;
    if (declarations.has(i)) continue;

    const previous = tokens[i - 1];
    const next = tokens[i + 1];

    if (previous && previous.type === 'symbol' && (previous.value === '.' || previous.value === ':')) continue;
    if (previous && previous.type === 'name' && previous.value === 'local') continue;
    // `local function name` - the name is the declaration, not a read of it.
    if (previous && previous.value === 'function' && tokens[i - 2] && tokens[i - 2].value === 'local') continue;
    // Table keys in a constructor are not reads of the local.
    if (next && next.value === '=' && previous && previous.type === 'symbol' && ['{', ','].includes(previous.value)) continue;

    if (token.line > declared) continue;
    if (boundAt.has(token.value) && boundAt.get(token.value) <= token.line) continue;

    errors.push(
      `${file}:${token.line}: '${token.value}' is used before its \`local\` on line ${declared} - that reads a global, which is nil`
    );
  }

  return errors;
}

function validate(file, source) {
  const scanned = tokenize(source, file);
  if (scanned.error) return [scanned.error];

  const errors = [];
  const tokens = scanned.tokens;
  const blocks = [];
  const brackets = [];

  // `for`/`while` are closed by the `do` that opens their body, so the very
  // next `do` keyword is already accounted for.
  let pendingDo = 0;

  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];

    if (token.type === 'symbol') {
      if (PAIRS[token.value]) {
        brackets.push(token);
      } else if (token.value === ')' || token.value === ']' || token.value === '}') {
        const open = brackets.pop();
        if (!open || PAIRS[open.value] !== token.value) {
          errors.push(`${file}:${token.line}: unbalanced '${token.value}'`);
        }
      }
      continue;
    }

    if (token.type !== 'name') continue;

    switch (token.value) {
      case 'function':
      case 'if':
        blocks.push({ open: token.value, line: token.line });
        break;
      case 'for':
      case 'while':
        blocks.push({ open: token.value, line: token.line });
        pendingDo++;
        break;
      case 'do':
        if (pendingDo > 0) pendingDo--;
        else blocks.push({ open: 'do', line: token.line });
        break;
      case 'repeat':
        blocks.push({ open: 'repeat', line: token.line });
        break;
      case 'end': {
        const top = blocks.pop();
        if (!top) errors.push(`${file}:${token.line}: unexpected 'end'`);
        else if (top.open === 'repeat') {
          errors.push(`${file}:${token.line}: 'repeat' at line ${top.line} closed by 'end'`);
        }
        break;
      }
      case 'until': {
        const top = blocks.pop();
        if (!top || top.open !== 'repeat') {
          errors.push(`${file}:${token.line}: unexpected 'until'`);
        }
        break;
      }
      default:
        break;
    }
  }

  for (const bracket of brackets) {
    errors.push(`${file}:${bracket.line}: unclosed '${bracket.value}'`);
  }
  for (const block of blocks) {
    errors.push(`${file}:${block.line}: '${block.open}' is never closed`);
  }

  if (/\breturn\b/.test(source.replace(/--.*$/gm, '')) === false) {
    errors.push(`${file}: module has no return statement`);
  }

  errors.push(...validateForwardLocals(file, tokens));

  // Accidental globals: `function name()` without `local` leaks into _G. Table
  // methods (`function Table.name()`) are the intended style and stay fine.
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.type !== 'name' || token.value !== 'function') continue;

    const previous = tokens[i - 1];
    const target = tokens[i + 1];
    const afterTarget = tokens[i + 2];

    if (afterTarget && (afterTarget.value === '.' || afterTarget.value === ':')) continue;

    const isLocal = previous && previous.type === 'name' && previous.value === 'local';
    const isExpression =
      previous && previous.type === 'symbol' && ['=', '(', ',', '{', 'return'].includes(previous.value);

    if (!isLocal && !isExpression && target && target.type === 'name') {
      errors.push(`${file}:${token.line}: 'function ${target.value}()' is a global - add \`local\``);
    }
  }

  return errors;
}

/**
 * `app.version` is what the running console prints, so it has to agree with the
 * version the install URLs are pinned to. It was a second hand-maintained copy of
 * `package.json`, which is how the sidebar ended up reporting a release that had
 * already been superseded.
 */
function validateVersion(file, source, version) {
  const errors = [];
  const pattern = /app\.version\s*=\s*"([^"]*)"/g;
  let match;

  while ((match = pattern.exec(source)) !== null) {
    if (match[1] === version) continue;
    const line = source.slice(0, match.index).split('\n').length;
    errors.push(`${file}:${line}: app.version is "${match[1]}" but package.json says "${version}"`);
  }

  return errors;
}

/** Every require("id") must resolve to a real module. */
function validateRequires(file, source, knownIds) {
  const errors = [];
  const pattern = /require\(\s*["']([^"']+)["']\s*\)/g;
  let match;

  while ((match = pattern.exec(source)) !== null) {
    const id = match[1];
    if (knownIds.has(id)) continue;
    const line = source.slice(0, match.index).split('\n').length;
    errors.push(`${file}:${line}: require("${id}") does not resolve to a module`);
  }

  return errors;
}

/* ---------------------------------------------------------------- bundler */

function toLongString(content) {
  let level = 1;
  while (content.includes(']' + '='.repeat(level) + ']')) level++;
  const equals = '='.repeat(level);
  return `[${equals}[\n${content.trim()}\n]${equals}]`;
}

function buildBridgeAssets() {
  const files = walk(BRIDGE).filter((file) => !file.endsWith('.md'));
  if (files.length === 0) return null;

  const entries = files
    .map((file) => {
      const id = path.relative(ROOT, file).replace(/\\/g, '/');
      const content = fs.readFileSync(file, 'utf8');
      return `\t[${JSON.stringify(id)}] = ${toLongString(content)},`;
    })
    .join('\n');

  return `__modules["bundle/assets"] = function(require)\n\t-- Raw text assets inlined from /bridge.\n\treturn {\n${entries}\n\t}\nend\n`;
}

function bundle(files, urls) {
  const install = urls
    ? `\tInstall (latest ${urls.coords.branch}):\n\t\t${oneLiner(urls.latest)}\n\tPinned to v${urls.coords.version}:\n\t\t${oneLiner(urls.pinned)}\n\n`
    : '';

  const banner = `--[[
\tRick & Morty AI Executor — bundled build
\tGenerated by build.js from /src. Do not edit this file by hand.
\tPaste the whole chunk into an executor and run it.

\tQuick menu : press ';'   |  Dashboard: run RickMortyAI:Open()  |  Unload: RickMortyAI:Unload()

${install}]]

--!nonstrict

local __modules, __cache = {}, {}

__modules["__root"] = function(require)
\treturn require
end

`;

  const modules = files
    .map((file) => {
      const id = moduleId(file);
      const body = fs
        .readFileSync(file, 'utf8')
        .replace(/^\uFEFF/, '')
        .trimEnd();
      return `__modules[${JSON.stringify(id)}] = function(require)\n${body}\nend\n`;
    })
    .join('\n');

  const runtime = `
local function __require(id)
\tlocal cached = __cache[id]
\tif cached ~= nil then
\t\treturn cached
\tend

\tlocal loader = __modules[id]
\tif not loader then
\t\terror("[RickMortyAI] module not found: " .. tostring(id), 2)
\tend

\tlocal result = loader(__require)
\t__cache[id] = result == nil and true or result
\treturn result
end

`;

  const bridge = buildBridgeAssets();
  return `${banner}${modules}\n${bridge ? bridge + '\n' : ''}${runtime}return __require(${JSON.stringify(ENTRY)})\n`;
}

/* ------------------------------------------------------------------- main */

function main() {
  const files = walk(SRC)
    .filter((file) => file.endsWith('.lua'))
    .sort();

  if (files.length === 0) {
    console.error('✗ no Luau modules found under src/');
    process.exit(1);
  }

  const knownIds = new Set([ENTRY, 'bundle/assets']);
  for (const file of files) knownIds.add(moduleId(file));

  const version = (repoCoordinates() || {}).version || '0.0.0';

  const errors = [];
  for (const file of files) {
    const source = fs.readFileSync(file, 'utf8');
    const id = moduleId(file) + '.lua';
    errors.push(...validate(id, source));
    errors.push(...validateRequires(id, source, knownIds));
    errors.push(...validateVersion(id, source, version));
  }

  if (errors.length > 0) {
    console.error(`✗ ${errors.length} validation problem(s):`);
    for (const error of errors) console.error('  - ' + error);
    process.exit(1);
  }

  console.log(`✓ validated ${files.length} modules`);

  const urls = rawUrls();

  if (!urls) {
    console.warn('  ! package.json has no usable repository field - install URL skipped');
  }

  if (checkOnly) {
    if (urls && syncReadme(urls, false) === 'updated') {
      console.warn('  ! README install block is out of date (run: npm run build)');
    }
    return;
  }

  // Every module must be reachable from the entry point.
  const source = files.map((file) => fs.readFileSync(file, 'utf8')).join('\n');
  for (const file of files) {
    const id = moduleId(file);
    if (id === ENTRY || id.startsWith('bundle/')) continue;
    const referenced =
      source.includes(`require("${id}")`) || source.includes(`require('${id}')`);
    if (!referenced) console.warn(`  ! ${id} is not required by any module`);
  }

  if (!fs.existsSync(DIST)) fs.mkdirSync(DIST, { recursive: true });
  fs.writeFileSync(OUT_FILE, bundle(files, urls), 'utf8');

  const size = (fs.statSync(OUT_FILE).size / 1024).toFixed(1);
  console.log(`✓ wrote dist/${OUT_FILE_NAME} (${size} kB)`);

  if (urls) {
    fs.writeFileSync(INSTALL_FILE, renderInstallFile(urls), 'utf8');
    console.log(`✓ wrote dist/install.lua -> ${urls.latest}`);

    const readme = syncReadme(urls, true);
    if (readme === 'updated') console.log('✓ updated the README install block');
    else if (readme === 'unchanged') console.log('✓ README install block already current');
    else console.warn('  ! README is missing the INSTALL markers - block not written');
  }
}

// Shared with verify-publish.js so the install URLs keep one source of truth.
module.exports = {
  repoCoordinates,
  rawUrls,
  oneLiner,
  OUT_FILE,
  OUT_FILE_NAME,
  BEGIN_MARK,
  END_MARK,
};

if (require.main === module) main();
